// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXIpHtv3PgYCy0FTV_eY79oCioBkecsQ',
    appId: '1:211475802277:web:5df4a57b3b49d721d4c54c',
    messagingSenderId: '211475802277',
    projectId: 'mabskie-47c24',
    authDomain: 'mabskie-47c24.firebaseapp.com',
    databaseURL: 'https://mabskie-47c24-default-rtdb.firebaseio.com',
    storageBucket: 'mabskie-47c24.firebasestorage.app',
    measurementId: 'G-XRKEZRL2YW',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEXIpHtv3PgYCy0FTV_eY79oCioBkecsQ',
    appId: '1:211475802277:web:226845b07318c2cad4c54c',
    messagingSenderId: '211475802277',
    projectId: 'mabskie-47c24',
    authDomain: 'mabskie-47c24.firebaseapp.com',
    databaseURL: 'https://mabskie-47c24-default-rtdb.firebaseio.com',
    storageBucket: 'mabskie-47c24.firebasestorage.app',
    measurementId: 'G-2L8654B0TG',
  );
}
